# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lin < Formula
  desc ""
  homepage "https://github.com/mufeez-amjad/lin"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mufeez-amjad/lin/releases/download/v0.0.2/lin_0.0.2_darwin_arm64.tar.gz"
      sha256 "0944ab8c2cc59316d29ca8a441535bc284ff65e14fe262b9d13e9a585222918f"

      def install
        bin.install "lin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mufeez-amjad/lin/releases/download/v0.0.2/lin_0.0.2_darwin_amd64.tar.gz"
      sha256 "24e0cd000996f82baa308057ffed991c2287641d5fa1f9e52bf324bd7fed33d8"

      def install
        bin.install "lin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mufeez-amjad/lin/releases/download/v0.0.2/lin_0.0.2_linux_amd64.tar.gz"
      sha256 "da947bc03951ac6194c732fd944c3ff429c927c2ad91ae8cba4c97958111a080"

      def install
        bin.install "lin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mufeez-amjad/lin/releases/download/v0.0.2/lin_0.0.2_linux_arm64.tar.gz"
      sha256 "47e49c3077f2e3f5b50e44fdcf3464bfee453071484519df7cbef212a63ba428"

      def install
        bin.install "lin"
      end
    end
  end
end
